#!/usr/local/bin/perl -w
# Copyright 2003, Buzzmaven Co.

# This file is part of Annotateit.

# Annotateit is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# Annotateit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Annotateit (see GNU-GPL.txt); if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA.
# The GNU General Public License may also be found on the Web at:
#   http://www.gnu.org/licenses/gpl.txt
use strict;
use Config::Simple qw(-strict);
use lib "../site_perl";
use Test::More qw(no_plan);
use widgets;
my $config = Config::Simple->new("../etc/test.conf");
my $dbh = &widgets::dbConnect($config);
my $user = $config->param('database.user');
my $password = $config->param('database.password');
my $database = $config->param('database.name');
`mysql -u $user -p$password $database < sql/ObjectDescription.sql`;

my @methods = qw( loadDescription saveDescription deleteDescription new _init 
		  ID ObjectClass Title 	);

BEGIN { use_ok( 'Rubric' ); }
require_ok('Rubric');
my $o = Rubric->new( dbh => $dbh );
isa_ok($o, 'Rubric');
can_ok($o, @methods);
$o->ID("1");
$o->Title("The First Rubric");
$o->ObjectClass("Rubric");
$o->OwnerID(1);
is($o->ID,1,"ID accessor methods");
is($o->Title,"The First Rubric", "Title accessor methods");
is($o->OwnerID,"1","OwnerID methods");
is($o->ObjectClass,"Rubric", "RubricClass accessor methds");
$o->save;
my $o2 = Rubric->new( dbh => $dbh );
$o2->load(ID => 1);
is_deeply($o2,$o,"Save/Load");
$o2->Title("Updated Rubric");
$o2->update;
$o->load;
is($o->Title,"Updated Rubric","Updated Object");

