package AnnotateitConfig;
use vars qw($C);

# general.notification sends notifications of annotations and errors.
# general.error_logs is the full path to the error logs of the apache server
#    so that error.cgi can find the last couple of lines and email it to you
#    if there is a problem.
# server.scriptdirectory is the absolute URL of the scripts in the cgi-bin
#    directory of this installation
# server.url is the url including the http:// and the port number (if running
#    on a port different from the standard port 80
# server.imagesdirectory is the absolute URL of the images in the images
#    directory of this installation
# server.documentdirectory is the absolute path to the directory in which
#    documents submitted by users will reside
# database.user is the username of the database user with access to the
#    annotateit database tables
# database.password is the password that goes with database.user
# database.name is the name of the database that database.user has access to
# database.host is the host name of the database that database.user has access
#    to and on which database.name resides.
# email.from is the email address that is used in the "from" field in
#    messages generated by annotateit

$C = { general => { notification => "Yes",
		    error_logs => "/usr/local/apache_test/logs/error_log" },
       server => { scriptdirectory=> "/perl/",
		   url=>"https://testing.annotateit.com:9443",
		   imagesdirectory=>"/images",
		   documentdirectory=>"/home/virtual/testing.annotateit.com/html/assignments",
		   documenturl=>"/assignments",
	       },
       database => {user=>"annotateit",
		    password=>"annotateit",
		    name=>"annotateit_com",
		    host=>"localhost"},
       email => {from=>"support\@annotateit.com"}
   };

1;
